services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD} # MARIADB_RANDOM_ROOT_PASSWORD
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes: 
      - db-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: "redis:latest"
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data 
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mariadb
      - redis
    volumes:
      - ${WWW_PATH}:/var/www/html # Dossier racine du serveur
      - ${CERTS_PATH}:/etc/apache2/ssl # Dossier contenant les certificats
      - ./conf/php/php.ini-development:/usr/local/etc/php/php.ini # Montre le fichier php.ini
      - ./conf/apache2/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf # Montre la config SSL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
